# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40bff8634d5fbf2834794444fc1a7558351dd5b352371e21bcd9d13ab3ec0e3de50203ad70d92b710c6967fd4cdeff8cec24f0e140087ea133d1449f8c8a8aa

test:
  secret_key_base: 0258d7ab1c855123b98e11924304e960531b7a83e752d517ee93b185c8be75ee2bbca2468e98f16589779ce5c546df60adece6a45627b80d39fbfab67fba38c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
